### ISSUE TITLE
Parse error Android 4.04 when installing latest legacy

### ISSUE THREAD

**Issue by kiwinol** [thanksmister/wallpanel-android-legacy#2]
**Describe the bug**
Should this version be compatible with android 4.04?
I receive a parse error when attempting to side load the latest legacy release.

**Smartphone (please complete the following information):**
 - Device: Toshiba AT100
 - OS: Android 4.04

**Comment by thanksmister** [comment]
Sorry, Android 4.1 is the minimum supported for this application.
