### ISSUE TITLE
Using Crosswalk engine Home Assistant 0.107 Lovelace stucks at "Initialising"

### ISSUE THREAD

**Issue by nagyrobi** [thanksmister/wallpanel-android-legacy#4]
Using Crosswalk Project browser engine trying to show Home Assistant 0.107.7's Lovelace interface stucks at "Initialising". Changing the browser engine to Android Webview loads Lovelace fine. 

For example using WallPanel standard version on my MT8127-based tablet, running Android 5.0.1, and on another Cortex-A7-based device running Android 7.1.2, although Webview is up-to date, Home Assistant's Lovelace is very laggy: Switches move slowly etc. 

With WallPanel Legacy and Crosswalk, it stucks at Loading, with WebView seems better than WallPanel standard.

Please replace the old Crosswalk with the more modern GeckoView engine, as Crosswalk seems dead and unusable now.

**Comment by thanksmister** [comment]
This project is no longer supported.
